name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from (usually 'main' or 'master')
  pull_request:
    branches:
      - main  # Optionally, you can deploy on pull requests as well

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Match this to the version you're using

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Export the app
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # This should match the output directory of the export command
          publish_branch: gh-pages  # The branch where you want to publish your site
